"use strict";
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || (function () {
    var ownKeys = function(o) {
        ownKeys = Object.getOwnPropertyNames || function (o) {
            var ar = [];
            for (var k in o) if (Object.prototype.hasOwnProperty.call(o, k)) ar[ar.length] = k;
            return ar;
        };
        return ownKeys(o);
    };
    return function (mod) {
        if (mod && mod.__esModule) return mod;
        var result = {};
        if (mod != null) for (var k = ownKeys(mod), i = 0; i < k.length; i++) if (k[i] !== "default") __createBinding(result, mod, k[i]);
        __setModuleDefault(result, mod);
        return result;
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
exports.PlantUMLAgent = void 0;
const fs = __importStar(require("fs"));
const path = __importStar(require("path"));
const path_1 = require("../../shared/utils/path");
class PlantUMLAgent {
    featuresDir;
    constructor(featuresDir) {
        this.featuresDir = featuresDir;
    }
    async generate(featureName, artifacts, types = ['class', 'sequence', 'component', 'usecase', 'activity']) {
        const outputs = [];
        const diagramDir = path.join(this.featuresDir, featureName, 'diagrams');
        (0, path_1.ensureDir)(diagramDir);
        for (const dt of types) {
            let output = null;
            switch (dt) {
                case 'class':
                    output = this.generateClassDiagram(featureName, artifacts);
                    break;
                case 'sequence':
                    output = this.generateSequenceDiagram(featureName, artifacts);
                    break;
                case 'component':
                    output = this.generateComponentDiagram(featureName, artifacts);
                    break;
                case 'usecase':
                    output = this.generateUseCaseDiagram(featureName, artifacts);
                    break;
                case 'activity':
                    output = this.generateActivityDiagram(featureName, artifacts);
                    break;
            }
            if (output) {
                const filePath = path.join(diagramDir, `${featureName}-${dt}.puml`);
                fs.writeFileSync(filePath, output.puml, 'utf-8');
                output.filePath = filePath;
                outputs.push(output);
            }
        }
        return outputs;
    }
    generateClassDiagram(featureName, artifacts) {
        const lines = [
            `@startuml ${featureName}-class`,
            `' Generated by herness PlantUML Agent`,
            `' Feature: ${featureName}`,
            ``,
            `skinparam classAttributeIconSize 0`,
            `skinparam classFontSize 12`,
            ``,
        ];
        const types = artifacts.types;
        const interfaceMatches = [...types.matchAll(/export\s+interface\s+(\w+)\s*\{([^}]*)\}/gs)];
        for (const match of interfaceMatches) {
            const name = match[1];
            const body = match[2].trim();
            lines.push(`class ${name} {`);
            const fieldLines = body.split('\n').map(l => l.trim()).filter(Boolean);
            for (const fl of fieldLines) {
                const fields = fl.split(';').map(f => f.trim()).filter(Boolean);
                for (const f of fields) {
                    const clean = f.replace(/[,;]$/, '').trim();
                    if (clean)
                        lines.push(`  +${clean}`);
                }
            }
            lines.push('}');
            lines.push('');
        }
        const moduleNames = artifacts.modules.map(m => {
            const colon = m.indexOf(':');
            return colon !== -1 ? m.slice(0, colon).trim() : m.trim();
        });
        if (moduleNames.length >= 2) {
            for (let i = 0; i < moduleNames.length - 1; i++) {
                const from = moduleNames[i];
                const to = moduleNames[i + 1];
                if (from !== to) {
                    lines.push(`${from} --> ${to}`);
                }
            }
        }
        const interview = artifacts.interview;
        if (interview) {
            const dataAnswers = interview.questions
                .filter(q => q.category === 'data_model' && q.resolved)
                .map(q => q.answer.toLowerCase());
            for (const answer of dataAnswers) {
                if (answer.includes('一对多') || answer.includes('1:n') || answer.includes('1-n')) {
                    const rels = answer.match(/(\w+)\s*(?:和|与)\s*(\w+)/);
                    if (rels) {
                        lines.push(`${rels[1]} "1" -- "*" ${rels[2]} : has`);
                    }
                }
                if (answer.includes('多对多') || answer.includes('n:n') || answer.includes('m:n')) {
                    const rels = answer.match(/(\w+)\s*(?:和|与)\s*(\w+)/);
                    if (rels) {
                        lines.push(`${rels[1]} "*" -- "*" ${rels[2]}`);
                    }
                }
            }
        }
        lines.push('@enduml');
        lines.push('');
        return {
            type: 'class',
            name: `${featureName} 类图`,
            puml: lines.join('\n'),
            description: `类图：${interfaceMatches.length} 个接口，${moduleNames.length} 个模块关系`,
            filePath: '',
        };
    }
    generateSequenceDiagram(featureName, artifacts) {
        const lines = [
            `@startuml ${featureName}-sequence`,
            `' Generated by herness PlantUML Agent`,
            ``,
        ];
        const interview = artifacts.interview;
        if (!interview) {
            lines.push(`actor User`);
            lines.push(`participant "${featureName}" as System`);
            lines.push(`User -> System: request`);
            lines.push(`System --> User: response`);
            lines.push('@enduml\n');
            return { type: 'sequence', name: `${featureName} 时序图`, puml: lines.join('\n'), description: '时序图：基本交互', filePath: '' };
        }
        const flowAnswers = interview.questions
            .filter(q => q.category === 'user_flow' && q.resolved)
            .map(q => q.answer);
        lines.push(`actor "用户" as User`);
        lines.push(`participant "${featureName}" as System`);
        lines.push('');
        const participants = new Set();
        const participantsAll = new Set();
        for (const flow of flowAnswers) {
            const steps = flow.split(/[,;，；。\n]/).map(s => s.trim()).filter(Boolean);
            for (const step of steps) {
                const mentions = step.match(/(?:调用|请求|接口|API|服务|Service|Gateway|数据库|DB|缓存|Cache|消息队列|MQ|外部)\s*[:：]?\s*(\w+)/g);
                if (mentions) {
                    for (const m of mentions) {
                        const name = m.replace(/(?:调用|请求|接口|API|服务|Service|Gateway|数据库|DB|缓存|Cache|消息队列|MQ|外部)\s*[:：]?\s*/, '').trim();
                        if (name && name.length > 1) {
                            participantsAll.add(name);
                            if (name !== 'System' && name !== 'User' && name !== '用户') {
                                participants.add(name);
                            }
                        }
                    }
                }
            }
        }
        for (const p of participants) {
            const clean = p.replace(/[^a-zA-Z0-9_\u4e00-\u9fa5]/g, '');
            if (clean)
                lines.push(`participant "${p}" as ${clean}`);
        }
        lines.push('');
        let stepNum = 0;
        for (const flow of flowAnswers) {
            const steps = flow.split(/[,;，；。\n]/).map(s => s.trim()).filter(Boolean);
            for (const step of steps) {
                if (step.length < 5)
                    continue;
                stepNum++;
                const clean = step.replace(/["']/g, '');
                if (clean.includes('返回') || clean.includes('响应') || clean.includes('return')) {
                    lines.push(`System --> User : ${stepNum}. ${clean.slice(0, 50)}`);
                }
                else {
                    lines.push(`User -> System : ${stepNum}. ${clean.slice(0, 50)}`);
                }
            }
        }
        lines.push('@enduml');
        lines.push('');
        return {
            type: 'sequence',
            name: `${featureName} 时序图`,
            puml: lines.join('\n'),
            description: `时序图：${flowAnswers.length} 个用户流程步骤`,
            filePath: '',
        };
    }
    generateComponentDiagram(featureName, artifacts) {
        const lines = [
            `@startuml ${featureName}-component`,
            `' Generated by herness PlantUML Agent`,
            ``,
            `skinparam componentStyle rectangle`,
            ``,
        ];
        const modules = artifacts.modules;
        const moduleNames = [];
        for (const m of modules) {
            const colon = m.indexOf(':');
            const name = colon !== -1 ? m.slice(0, colon).trim() : m.trim();
            moduleNames.push(name);
            lines.push(`component "${name}"`);
        }
        lines.push('');
        const interfaces = artifacts.interfaces.filter(i => i.startsWith('`') && i.endsWith('`'));
        if (interfaces.length > 0) {
            lines.push(`package "Contracts" {`);
            lines.push(`  interface "${interfaces[0].replace(/`/g, '')}" as Contract`);
            lines.push('}');
            lines.push('');
            if (moduleNames.length > 0) {
                lines.push(`${moduleNames[0]} ..> Contract`);
            }
        }
        if (moduleNames.length >= 2) {
            lines.push('');
            for (let i = 0; i < moduleNames.length - 1; i++) {
                lines.push(`${moduleNames[i]} --> ${moduleNames[i + 1]} : depends on`);
            }
        }
        const interview = artifacts.interview;
        if (interview) {
            const integrationAnswers = interview.questions
                .filter(q => q.category === 'integration' && q.resolved)
                .map(q => q.answer);
            for (const int of integrationAnswers) {
                const system = int.slice(0, 30).replace(/[：:]/g, '').trim();
                if (system && moduleNames.length > 0) {
                    lines.push(`${moduleNames[0]} --> "${system}" : external`);
                }
            }
        }
        lines.push('@enduml');
        lines.push('');
        return {
            type: 'component',
            name: `${featureName} 组件图`,
            puml: lines.join('\n'),
            description: `组件图：${moduleNames.length} 个组件${interfaces.length > 0 ? `，${interfaces.length} 个接口` : ''}`,
            filePath: '',
        };
    }
    generateUseCaseDiagram(featureName, artifacts) {
        const lines = [
            `@startuml ${featureName}-usecase`,
            `' Generated by herness PlantUML Agent`,
            ``,
            `left to right direction`,
            `actor "用户" as User`,
            ``,
            `rectangle "${featureName}" {`,
        ];
        const acSection = artifacts.interview?.featureContent?.match(/##\s*验收标准\s*\n([\s\S]*?)(?=\n##|$)/);
        const acLines = [];
        if (acSection) {
            const items = acSection[1].matchAll(/-\s*\[.?\]?\s*(.+)/g);
            for (const item of items) {
                acLines.push(item[1].trim());
            }
        }
        if (acLines.length === 0) {
            lines.push(`  usecase "核心功能" as UC1`);
            lines.push(`}`);
        }
        else {
            for (let i = 0; i < acLines.length; i++) {
                const clean = acLines[i].slice(0, 30).replace(/["']/g, '');
                lines.push(`  usecase "${clean}" as UC${i + 1}`);
            }
            lines.push(`}`);
            lines.push('');
            for (let i = 0; i < acLines.length; i++) {
                lines.push(`User --> UC${i + 1}`);
            }
        }
        lines.push('@enduml');
        lines.push('');
        return {
            type: 'usecase',
            name: `${featureName} 用例图`,
            puml: lines.join('\n'),
            description: `用例图：${acLines.length || 1} 个用例`,
            filePath: '',
        };
    }
    generateActivityDiagram(featureName, artifacts) {
        const lines = [
            `@startuml ${featureName}-activity`,
            `' Generated by herness PlantUML Agent`,
            ``,
            `start`,
        ];
        const interview = artifacts.interview;
        let activityCount = 0;
        if (interview) {
            const flowAnswers = interview.questions
                .filter(q => q.category === 'user_flow' && q.resolved)
                .map(q => q.answer);
            for (const flow of flowAnswers) {
                const steps = flow.split(/[,;，；。\n]/).map(s => s.trim()).filter(Boolean);
                for (const step of steps) {
                    if (step.length < 5)
                        continue;
                    const clean = step.slice(0, 40).replace(/["'\\]/g, '');
                    activityCount++;
                    lines.push(`:${clean};`);
                }
            }
            const edgeAnswers = interview.questions
                .filter(q => q.category === 'edge_cases' && q.resolved)
                .map(q => q.answer);
            for (const edge of edgeAnswers) {
                const points = edge.split(/[。\n]/).filter(Boolean);
                for (const p of points.slice(0, 2)) {
                    const clean = p.trim().slice(0, 30).replace(/["'\\]/g, '');
                    if (clean) {
                        lines.push(`if (${clean}?) then (yes)`);
                        lines.push(`  :处理异常;`);
                        lines.push(`else (no)`);
                        lines.push(`  :继续;`);
                        lines.push(`endif`);
                        activityCount++;
                    }
                }
            }
        }
        if (activityCount === 0) {
            lines.push(`:执行功能;`);
            lines.push(`if (成功?) then (yes)`);
            lines.push(`  :返回结果;`);
            lines.push(`else (no)`);
            lines.push(`  :返回错误;`);
            lines.push(`endif`);
        }
        lines.push('stop');
        lines.push('@enduml');
        lines.push('');
        return {
            type: 'activity',
            name: `${featureName} 活动图`,
            puml: lines.join('\n'),
            description: `活动图：${activityCount || 1} 个步骤`,
            filePath: '',
        };
    }
}
exports.PlantUMLAgent = PlantUMLAgent;
//# sourceMappingURL=index.js.map